config/routes.rb
Rails.application.routes.draw do
  # don't use Devise namespace for omniauth callbacks (will inherit from existing class instead):
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" } 

  resources :products, only: [:index, :show]

  resources :order_items, except: [:create]
  post 'order_items/add/(:product_id)', to: 'order_items#create', as: "add_order_item"
  patch 'order_items/update', to: 'order_items#update', as: "update_order_item"

  patch 'orders/checkout', to: 'orders#checkout', as: "checkout_order"

  root to: "products#index"

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :user
  has_many :orders

end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_items, dependent: :destroy
  belongs_to :user
  belongs_to :address

  extend FirstOrBuild

  def subtotal
    order_items.map(&:subtotal).reduce(:+) || 0
  end

  def item_count
    order_items.map(&:quantity).reduce(:+) || 0
  end

  def percent_discount
    if user && user.verified?
      case user.affiliation
      when "Service Member", "Veteran", "Military Spouse", "Military Family", "Retiree"
        0.1
      else
        0.0
      end 
    else
      0.0
    end
  end

  def discount
    -(subtotal * percent_discount) 
  end

  def shipping
    item_count * 2.50
  end

  def total
    (subtotal * (1 - percent_discount)) + shipping
  end



end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product

  def subtotal
    quantity * product.price
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :order_items

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:idme]

  validates_presence_of :username # Devise won't do this by default.

  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy


  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |u|
      u.provider = auth[:provider]
      u.uid = auth[:uid]
      u.verified = auth[:info][:verified]
      u.affiliation = auth[:info][:affiliation]
    end
  end

  # If using ID.me as SSO, additional info such as email would be available in authorization hash.

  def self.new_with_session(params, session)
    super.tap do |u|
      if data = session["devise.user_attributes"] 
        u.attributes = ActionController::Parameters.new(data)
          .permit(:provider, :uid, :affiliation, :verified)
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    whitelist = ->(u) { u.permit(:username, :email, :password, :password_confirmation,
                                 :current_password, :provider, :uid, :affiliation) }
    devise_parameter_sanitizer.for(:sign_up, &whitelist)
    devise_parameter_sanitizer.for(:account_update, &whitelist)
    # devise_parameter_sanitizer.for(:sign_in, &whitelist)
  end

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def idme
    @user = User.from_omniauth(auth_hash)
    if @user.persisted?

      sign_in_and_redirect @user
      set_flash_message(:notice, :success, kind: "ID.me") if is_navigational_format?
    else
      # persist attributes in session so validation errors can be displayed if needed.
      # devise will remove the attributes later when the session is destroyed.
      session["devise.user_attributes"] = @user.attributes
      redirect_to new_user_registration_url
    end
  end

  def auth_hash
    # puts request.inspect
    auth = request.env["omniauth.auth"]
    # persist raw response in session to display to user when signed in.
    # devise will remove the hash later when the session is destroyed.
    session["omniauth_raw"] = auth[:extra][:raw]
    ActionController::Parameters.new(auth)
      .permit(:provider, :uid, info: [:affiliation, :verified])
  end
  protected :auth_hash

end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  before_action :authenticate_user!

  def create
    load_order.order_items.create(product_id: params[:product_id])
    flash[:success] = 'Successfully added product to cart.'
    redirect_to order_items_path
  end

  def index
    @order = load_order
    @order_items = @order.order_items
  end

  def update
    OrderItem.find(params[:id]).update(update_params)
    flash[:success] = 'Shopping cart updated.'
    redirect_to order_items_path
  end

  def load_order
    order = Order.where(id: session[:order_id], status: "unsubmitted").first_or_create do |order|
      order.user_id = current_user.id if user_signed_in?
    end
    session[:order_id] = order.id
    order
  end

  private

  def update_params
    params.require(:order_item).permit(:quantity)
  end


end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def checkout
    Order.find(session[:order_id]).update(status: "submitted")

    flash[:success] = "Thank you for shopping with us! If we were a real company, " +
                      "an email confirmation would be arriving soon."
    redirect_to root_path
    session[:order_id] = nil  
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @omniauth_raw = session.delete("omniauth_raw")
    @products = Product.order("name").page(params[:page]).per_page(20)
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  private
    def product_params
      params.require(:product).permit(:name, :description, :price, :stock)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
 
  def bootstrap_class_for(flash_type)
    f = flash_type.to_s
    { "success" => "success", "error" => "danger", 
      "alert" => "warning", "notice" => "info" }[f] || f
  end
     
end 

app/helpers/devise_helper.rb
module DeviseHelper
  # Display devise error messages using the same flash style as the rest of the app. 
  def devise_error_messages!
    unless resource.errors.empty?
      flash[:error] = resource.errors.full_messages.map do |msg| 
        content_tag(:li, msg) 
      end.join.html_safe
    end
    return ''
  end
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_flash.html.haml
- flash.each do |key, msg|
  .alert.fade.in.alert-dismissible{class: "alert-#{bootstrap_class_for(key)}", role: "alert"}
    %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
      %span{"aria-hidden" => "true"} &times;
    = msg

app/views/layouts/_footer.html.haml
%footer

app/views/layouts/_header.html.haml
%body
  %header
    %nav.navbar.navbar-default{:role => "navigation"}
      .container-fluid
        .navbar-header
          %strong
            %a.navbar-brand{:href => "/"} Implausible Products
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              Menu
              %span.caret
            %ul.dropdown-menu{:role => "menu"}
              %li= link_to 'Home', root_path
              - if user_signed_in?
                %li= link_to "Shopping cart", order_items_path
                %li.divider
                %li= link_to "View orders", "#"
                %li= link_to 'Edit profile', edit_user_registration_path
                %li
                  = link_to "Sign out #{current_user.email}", destroy_user_session_path, :method => :delete
              - else
                %li= link_to "Log in", new_user_session_path
                %li= link_to "Log in with ID.me", user_omniauth_authorize_path(:idme)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Oauth2Consumer
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container-fluid
      = render "layouts/header"
    .container
      = render "layouts/flash"
      = yield
      = render "layouts/footer"

app/views/order_items/index.html.haml
%h3.page-header Your items (#{@order.item_count}):

.table-responsive
  %table.table.table-hover
    %thead
      %tr
        %th Name
        %th Price
        %th Quantity
        %th Subtotal
    %tbody
      - @order_items.each do |item|
        %tr
          %td= link_to item.product.name, product_path(item.product.id)
          %td= number_to_currency(item.product.price, precision: 2)
          %td
            = form_for(item) do |f| 
              = f.number_field :quantity, min: 0
              = f.submit "update", class: "btn btn-sm btn-default"
          %td= number_to_currency(item.subtotal, precision: 2)
    %tfoot
      %tr
        %td{colspan: "2"}
        %td 
          %strong Subtotal: 
        %td 
          %strong #{number_to_currency(@order.subtotal, precision: 2)}
      %tr
        %td{colspan: "2"}
        %td 
          %strong Discount: 
        %td 
          %strong #{number_to_currency(@order.discount, precision: 2)}
      %tr
        %td{colspan: "2"}
        %td 
          %strong Shipping: 
        %td 
          %strong #{number_to_currency(@order.shipping, precision: 2)}
      %tr
        %td{colspan: "2"}
        %td 
          %strong Total: 
        %td 
          %strong #{number_to_currency(@order.total, precision: 2)}
      %tr
        %td{colspan: "3"}
        %td
          - if @order.item_count > 0
            %p= button_to "Checkout", checkout_order_path, method: :patch, class: "btn btn-primary btn-default"
          %p= link_to "Continue shopping", root_path, class: "btn btn-primary btn-default"

app/views/products/index.html.haml
- if @omniauth_raw
  = render 'omniauth_callbacks/payload_display'
- else
  = render 'shared/idme_troop'

%h3.page-header#main-products-header Our Products
= will_paginate @products
.table-responsive
  %table.table.table-hover
    %thead
      %tr
        %th Name
        %th Description
        %th Price
        %th{colspan: "3"}
    %tbody
      - @products.each do |product|
        %tr
          %td= link_to product.name, product
          %td= product.description
          %td= number_to_currency(product.price, precision: 2)
          %td
            - if product.stock > 0
              = button_to "Add to Cart", add_order_item_path(product_id: product.id), class: "btn btn-primary btn-default"
            - else
              "Out of stock"
= will_paginate @products

app/views/products/show.html.haml
%jumbotron
  %h1.page-header
    = @product.name
  %p
    = @product.description
  %p
    %strong Price:
    = number_to_currency(@product.price, precision: 2)
  %p
    %strong Stock:
    = @product.stock > 0 ? "Available" : "Out of stock"
  %p
    = link_to "Back", :back, class: "btn btn-primary btn-default"
    = link_to "Add to cart", add_order_item_path(product_id: @product.id), class: "btn btn-primary btn-default"

app/views/shared/_idme_troop.html.haml
#military-discount-panel.panel.panel-primary
  .panel-heading
    %button.close{"data-dismiss" => "alert", "data-target" => "#military-discount-panel", :type => "button"}
      %span{"aria-hidden" => "true"} ×
      %span.sr-only Close
    .panel-title Military discount
  .panel-body
    .idme-btn-container
      %a.idme-btn{:href => "#{user_omniauth_authorize_path(:idme)}"}
        %img.idme-btn-primary-sm-Troop{:alt => "Verify with ID.me Troop ID", :border => "0", :src => "https://s3.amazonaws.com/idme/buttons/new/btn-primary-sm-Troop.png"}/
      %span.idme-btn-affinity 
        Military? 
        = link_to " log in with ID.me ", user_omniauth_authorize_path(:idme)
        and receive 10% off your purchase!
      %span.idme-btn-verification
        %img.idme-btn-lock{:alt => "Lock", :src => "https://s3.amazonaws.com/idme/assets/lock.png", :width => "8"}>/
        = " Verification by ID.me"
        %br/
        %a#modal-open{:href => "https://www.id.me/how-it-works"} • What is ID.me?